### ISSUE TITLE
i want these questions solution

### ISSUE THREAD

**Issue by Kishansharma06** [Kishansharma06/coding_ques#1]
653. Two Sum IV - Input is a BST
1. Two Sum
2. Add Two Numbers
3. Longest Substring Without Repeating Characters
4. Median of Two Sorted Arrays
5. Longest Palindromic Substring
6. Zigzag Conversion
7. Reverse Integer
8. String to Integer (atoi)

**Comment by iammk31** [comment]
!assign this

**Comment by kalaSriSaiRaksha** [comment]
please assign this issue to me
